### ISSUE TITLE
mzR on Windows 10 with x64 JDK

### ISSUE THREAD

**Issue by FlorianEndel** [statistikat/mzR#6]
While installing the `mzR` package works flawlessly in (my) debian 10 environment and [docker/rocker](https://github.com/rocker-org/rocker), I ran into some troubles on Windows 10 x64. Although R and JDK are installed as i386 and x64 applications, automatic testing of the mzR package fails for the i386 architecture:

> ** testing if installed package can be loaded from temporary location
> *** arch - i386
> Error: package or namespace load failed for 'mzR':
>  .onLoad failed in loadNamespace() for 'rJava', details:
>   call: inDL(x, as.logical(local), as.logical(now), ...)
>   error: kann shared object 'C:/Users/Florian Endel/Documents/R/win-library/3.6/rJava/libs/i386/rJava.dll' nicht laden:
>   LoadLibrary failure:  %1 ist keine zulässige Win32-Anwendung.

I found several (rather old) hints, that there might be an issue with the automatic multi-arch testing when rJava is involved. As I do not need the i386 version I might as well not install and test it:

`devtools::install_github("statistikat/mzR", build_opts = c("--no-resave-data"), INSTALL_opts = c("--no-multiarch"))`

Perhaps this alteration can help others installing the package on Windows.

> platform       x86_64-w64-mingw32          
> arch           x86_64                      
> os             mingw32                     
> system         x86_64, mingw32             
> status                                     
> major          3                           
> minor          6.2                         
> year           2019                        
> month          12                          
> day            12                          
> svn rev        77560                       
> language       R                           
> version.string R version 3.6.2 (2019-12-12)
> nickname       Dark and Stormy Night

**Comment by alexkowa** [comment]
Thank you. This seems to be a problem of the dependency XLConnect since this is using Java.
